# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Massimo De Agrò
# Description of the Site
description: Attaching bugs to computers since 2020
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: research, spider cognition, spider vision, spider eye, spoder
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://massimodeagro.github.io/assets/images/hero.webp

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: massimo.deagro@unitn.it
facebook_username: 
twitter_username: Massimo_De_Agro
instagram_username: 
linkedin_username: 
github_username:  massimodeagro
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 
researchgate_username: Massimo-De-Agro
orcid_username: 0000-0001-9284-5964

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Massimo De Agrò
# URL for the Image of the Author
author-image: https://massimodeagro.github.io/assets/images/photo.jpg
# 60 Words About the Author
author-about: "Post-doc researcher at CIMeC, University of Trento, Italy. I study cognition and perception in arthropods using automated procedures. I am fascinated by how minuscule brains solve the problem of limited neural capacity when faced with complex stimuli. My research tries to identify processes of simplification and clever circuitry."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://massimodeagro.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
